---
cirrus-ci_task:
  container:
    image: l.gcr.io/google/bazel:2.1.0
    cpu: 8
    memory: 12G
  configure_script:
    - sudo apt update
    - sudo apt install -y
        autopoint
        libasound2-dev
        libcv-dev
        libhighgui-dev
        libopenal-dev
        x264-dev
        ffmpeg-dev
    - echo "build --jobs=50 --curses=no --verbose_failures" | sudo tee /etc/bazel.bazelrc
    - echo "build --config=linux" | sudo tee -a /etc/bazel.bazelrc
    - echo "build --config=gcc" | sudo tee -a /etc/bazel.bazelrc
    - echo "build --config=remote" | sudo tee -a /etc/bazel.bazelrc
    - cd .. && mv cirrus-ci-build c-toxcore
    - git clone --branch=upgrade-bazel --depth=1 https://github.com/iphydf/toktok-stack cirrus-ci-build
    - mv c-toxcore cirrus-ci-build
    - cd -
    - bazel version
  test_all_script:
    - bazel test --copt=-DUSE_IPV6=0 -c opt -k //c-toxcore/...
