name: amalgamation_test_win64_vcpkg

on:
  push:
  pull_request:

jobs:
  amalgamation_test_win64_vcpkg:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: update vcpkg
        shell: bash
        run: |
          cd C:/vcpkg
          git pull

      - name: Install Dependencies
        run: |
          vcpkg install pkgconf:x64-windows libsodium:x64-windows-static pthreads:x64-windows-static

      - name: find packages
        shell: bash
        run: |
          cd C:/vcpkg
          find . -name '*.pc'

      - name: find pthreads libs
        shell: bash
        run: |
          cd C:/vcpkg/packages/pthreads_x64-windows-static/
          find .

      - name: find sodium libs
        shell: bash
        run: |
          cd C:/vcpkg/packages/libsodium_x64-windows-static/
          find .

      - name: checks
        run: |
          cd C:/vcpkg
          vcpkg
          C:/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --list-all --with-path=C:/vcpkg/installed/x64-windows/lib/pkgconfig
          C:/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --list-all --with-path=C:/vcpkg/packages/libsodium_x64-windows-static/lib/pkgconfig
          C:/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --libs --cflags --with-path=C:/vcpkg/packages/libsodium_x64-windows-static/lib/pkgconfig libsodium

      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@release/v1

      - name: compiler
        shell: cmd
        run: |
          echo %PATH%
          cl.exe

      - name: compile
        run: |
          cd amalgamation
          cl /MT amalgamation_test.c User32.lib Ws2_32.lib wsock32.lib iphlpapi.lib pthreadVC3.lib libsodium.lib /I"C:/vcpkg/packages/pthreads_x64-windows-static/include" /I"C:/vcpkg/packages/libsodium_x64-windows-static/include" /link /LIBPATH:"C:/vcpkg/packages/libsodium_x64-windows-static/lib" /LIBPATH:"C:/vcpkg/packages/pthreads_x64-windows-static/lib" /SUBSYSTEM:CONSOLE

