name: amalgamation_test_win64_vcpkg

on:
  push:
  pull_request:

jobs:
  amalgamation_test_win64_vcpkg:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

#      - name: find c compiler
#        shell: bash
#        run: |
#          cd C:/
#          find . -name 'cl.exe'

      - name: update vcpkg
        shell: bash
        run: |
          cd C:/vcpkg
          git pull

      - name: Install Dependencies
        run: |
          vcpkg install pkgconf:x64-windows libsodium:x64-windows-static pthreads:x64-windows-static

      - name: find packages
        shell: bash
        run: |
          cd C:/vcpkg
          find . -name '*.pc'

      - name: test
        run: |
          cd C:/vcpkg
          vcpkg
          C:/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --list-all --with-path=C:/vcpkg/installed/x64-windows/lib/pkgconfig
          C:/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --list-all --with-path=C:/vcpkg/packages/libsodium_x64-windows-static/lib/pkgconfig
          C:/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --libs --cflags --with-path=C:/vcpkg/packages/libsodium_x64-windows-static/lib/pkgconfig libsodium

      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@release/v1

      - name: compile
        shell: cmd
        run: |
          echo %PATH%
          cl.exe

