name: netbsd build

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  build-netbsd:
    runs-on: ubuntu-latest
    name: NetBSD Build
    env:
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: compile in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          /usr/sbin/pkg_add curl

        run: |
          pwd
          ls -lah
          whoami
          env
