name: netbsd build

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  build-netbsd:
    runs-on: ubuntu-latest
    name: NetBSD Build
    env:
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: compile in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          /usr/sbin/pkg_add
            curl
            cmake
            googletest
            libconfig
            libopus
            libsodium
            libvpx
            x264
            libavcodec
            libavformat
            libavdevice
            pkg-config

        run: |
           pwd
           cmake . \
              -DMUST_BUILD_TOXAV=ON \
              -DNON_HERMETIC_TESTS=ON \
              -DTEST_TIMEOUT_SECONDS=300 \
              -DUSE_IPV6=OFF \
              -DAUTOTEST=ON
            cmake --build . --target install
            ctest -j50 --output-on-failure --rerun-failed --repeat until-pass:6

