name: windows_build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: choco install ffmpeg -y

      - run: git clone https://github.com/Microsoft/vcpkg.git
      - run: |
          cd vcpkg
          ./bootstrap-vcpkg.bat -disableMetrics
          ./vcpkg --disable-metrics install libsodium
          ./vcpkg --disable-metrics integrate install

      - run: cmake --version
      - run: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="D:/a/c-toxcore/c-toxcore/vcpkg/scripts/buildsystems/vcpkg.cmake"



