name: windows_build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: choco install ffmpeg -y

      - run: git clone https://github.com/Microsoft/vcpkg.git
      - run: |
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg install libsodium
          ./vcpkg integrate install

      - run: cmake --version
      - run: cmake -G "Visual Studio 17 2022"



